name = "BELY AI"
client_id = "0c6c69853d601c94138ac794687a25c0"
application_url = "https://belyshield.com"
embedded = true

[auth]
redirect_urls = [
  "https://belyshield.com/auth-callback.html",
  "https://bely-ai.vercel.app/auth-callback.html"
]

[webhooks]
api_version = "2026-04"

[pos]
embedded = false
